language: go

go:
  - 1.8

notifications:
  email: false

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls

script:
  - overalls -project=github.com/maprost/restclient -covermode=count -debug
  - goveralls -coverprofile=overalls.coverprofile -service semaphore -repotoken $COVERALLS_TOKEN