language: go

go:
  - 1.8

notifications:
  email: false

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls

script:
  - overalls -covermode=count
  - goveralls -coverprofile=test.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN